#!/usr/bin/env bash
set -euxo pipefail

# == enabel tap service ==
install -D --mode=755 "$SDK/files/setup-tap0" \
  "$HOME/.local/bin/setup-tap0"

install -D --mode=644 "$SDK/files/setup-tap0.service" \
  "$HOME/.config/systemd/user/setup-tap0.service"

systemctl --user daemon-reload
systemctl --user enable --now setup-tap0.service
