#!/usr/bin/env bash
set -euxo pipefail

## == clone and build opensbi ==
OPENSBI_VERSION="v1.8.1"
OPENSBI_URL="https://github.com/riscv-software-src/opensbi.git"

echo "[rkc-toolchain] OpenSBI version: ${OPENSBI_VERSION}"
echo "[rkc-toolchain] OpenSBI url: ${OPENSBI_URL}"

if [ ! -d opensbi ]; then
  git clone \
    --depth=1 \
    --branch="${OPENSBI_VERSION}" \
    --single-branch \
    "${OPENSBI_URL}" \
    opensbi
fi

if [ ! -f opensbi/build/platform/generic/firmware/fw_jump.bin ]; then
  export CROSS_COMPILE=riscv64-linux-gnu-
  make -C opensbi PLATFORM=generic
fi

# == enabel tap service ==
install -D --mode=755 "$SDK/files/setup-tap0" \
  "$HOME/.local/bin/setup-tap0"

install -D --mode=644 "$SDK/files/setup-tap0.service" \
  "$HOME/.config/systemd/user/setup-tap0.service"

systemctl --user daemon-reload
systemctl --user enable --now setup-tap0.service
