#!/usr/bin/env bash
set -euxo pipefail

cd /project

# == install required packages ==
sudo apt-get update
sudo apt-get install -y \
  ca-certificates \
  curl \
  git \
  make \
  python3 \
  clang \
  lld \
  llvm \
  qemu-system-misc \
  qemu-utils \
  device-tree-compiler \
  build-essential \
  libglib2.0-dev \
  libpixman-1-dev \
  gcc-riscv64-linux-gnu

## == verify versions ==
qemu-system-riscv64 --version
clang --version