{.warning[UnusedImport]: off.}

import lib/mem
import lib/string
import lib/types

discard sizeof(CSize)

when defined(userApp_shell):
  import apps/shell/shell
elif defined(userApp_ls):
  import apps/ls/ls
elif defined(userApp_cat):
  import apps/cat/cat
elif defined(userApp_mkdir):
  import apps/mkdir/mkdir
elif defined(userApp_ps):
  import apps/ps/ps
elif defined(userApp_rm):
  import apps/rm/rm
elif defined(userApp_rmdir):
  import apps/rmdir/rmdir
elif defined(userApp_date):
  import apps/date/date
elif defined(userApp_edit):
  import apps/edit/edit
elif defined(userApp_ipc):
  import apps/ipc/ipc
elif defined(userApp_kill):
  import apps/kill/kill
elif defined(userApp_svc):
  import apps/svc/svc
elif defined(userApp_ping):
  import apps/ping/ping
elif defined(userApp_nslookup):
  import apps/nslookup/nslookup
elif defined(userApp_tcpcheck):
  import apps/tcpcheck/tcpcheck
elif defined(userApp_curl):
  import apps/curl/curl
elif defined(userApp_svcmgtd):
  import server/svcmgtd/svcmgtd
elif defined(userApp_procmgtd):
  import server/procmgtd/procmgtd
elif defined(userApp_fsd):
  import server/fsd/fsd
elif defined(userApp_blockd):
  import server/blockd/blockd
elif defined(userApp_procfsd):
  import server/procfsd/procfsd
elif defined(userApp_netd):
  import server/netd/netd
elif defined(userApp_stracectl):
  import apps/stracectl/stracectl
elif defined(userApp_dmesg):
  import apps/dmesg/dmesg
elif defined(userApp_rkxinfo):
  import apps/rkxinfo/rkxinfo
elif defined(userApp_echo):
  import apps/echo/echo
elif defined(userApp_touch):
  import apps/touch/touch
elif defined(userApp_cp):
  import apps/cp/cp
elif defined(userApp_mv):
  import apps/mv/mv
elif defined(userApp_df):
  import apps/df/df
elif defined(userApp_wc):
  import apps/wc/wc
# == test use only apps ==
elif defined(userApp_faultcheck):
  import apps/faultcheck/faultcheck
elif defined(userApp_capcheck):
  import apps/capcheck/capcheck
elif defined(userApp_pollcheck):
  import apps/pollcheck/pollcheck
elif defined(userApp_signalcheck):
  import apps/signalcheck/signalcheck
else:
  {.error: "missing user app define".}
