#!/usr/bin/env bash
set -euxo pipefail

cd /project

# == install required packages ==
sudo apt-get update
sudo apt-get install -y \
  curl \
  ca-certificates \
  git \
  make

## == install act ==
curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b /usr/local/bin
act --version
