import ../../lib/core/io


proc printHelp*() =
  write("available commands:\n")
  write("  help\n")
  write("  cd\n")
  write("  ls\n")
  write("  cat\n")
  write("  mkdir\n")
  write("  rm\n")
  write("  rmdir\n")
  write("  echo\n")
  write("  touch\n")
  write("  cp\n")
  write("  mv\n")
  write("  edit\n")
  write("  ps\n")
  write("  date\n")
  write("  ipc\n")
  write("  kill\n")
  write("  svc\n")
  write("  ping\n")
  write("  nslookup\n")
  write("  curl\n")
  write("  tcpcheck\n")
  write("  stracectl\n")
  write("  dmesg\n")
  write("  ticks\n")
  write("  traps\n")
  write("  bitmap\n")
  write("  history\n")
  write("  exit\n")
  write("  shutdown\n")
  write("\n")
  write("run '<command> --help' for app help\n")
  write("append '&' to run app commands in background\n")
