## Prints the compact shell command list and points apps to --help.
import ../../lib/core/io


## Displays available shell commands and the app help convention.
proc printHelp*() =
  write("available commands:\n")
  write("  help\n")
  write("  login\n")
  write("  cd\n")
  write("  su\n")
  write("  ls\n")
  write("  cat\n")
  write("  mkdir\n")
  write("  rm\n")
  write("  rmdir\n")
  write("  echo\n")
  write("  touch\n")
  write("  ec\n")
  write("  cp\n")
  write("  mv\n")
  write("  df\n")
  write("  cpuinfo\n")
  write("  id\n")
  write("  chmod\n")
  write("  chown\n")
  write("  passwd\n")
  write("  edit\n")
  write("  ps\n")
  write("  date\n")
  write("  ipc\n")
  write("  kill\n")
  write("  svc\n")
  write("  ping\n")
  write("  nslookup\n")
  write("  curl\n")
  write("  tcpcheck\n")
  write("  stracectl\n")
  write("  dmesg\n")
  write("  ticks\n")
  write("  traps\n")
  write("  bitmap\n")
  write("  history\n")
  write("  which\n")
  write("  exit\n")
  write("  shutdown\n")
  write("\n")
  write("run '<command> --help' for app help\n")
  write("append '&' to run app commands in background\n")
