"""Filesystem, namespace, ownership, and file operation smoke test cases."""
from .model import TestCase


def filesystem_tests() -> list[TestCase]:
    """Returns root filesystem and development namespace behavior tests."""
    return [
        TestCase("ls root dirs", "ls /", ["var/", "usr/"], not_contains=["var/log/"]),
        TestCase("ls /var", "ls /var", ["log/"]),
        TestCase("ls /usr development namespace", "ls /usr", ["bin/", "src/", "include/", "lib/"]),
        TestCase("ls -l /usr ownership", "ls -l /usr", ["drwxr-xr-x", "root:root", "bin/", "src/", "include/", "lib/"]),
        TestCase("root places executable under /usr/bin", "cp /bin/echo /usr/bin/dev_echo", []),
        TestCase("rootfs executable initially not executable", "/usr/bin/dev_echo blocked", ["permission denied: /usr/bin/dev_echo"]),
        TestCase("root enables executable under /usr/bin", "chmod 755 /usr/bin/dev_echo", []),
        TestCase("root executes /usr/bin binary", "/usr/bin/dev_echo phase0-root", ["phase0-root"]),
        TestCase("ls /bin", "ls /bin", ["shell", "svcmgtd", "tcpcheck", "curl", "dmesg"], not_contains=["./", "../"]),
        TestCase("ls -a dot entries", "ls -a /bin", ["./", "../", "shell"]),
        TestCase("ls -al dot entries", "ls -al /bin", ["./", "../", "shell", "bytes"]),
        TestCase("ls parent path", "ls /bin/..", ["bin/", "tmp/"]),
        TestCase("ls -l /bin", "ls -l /bin", ["shell", "bytes"]),
        TestCase("touch chmod target", "touch /tmp/chmod_smoke", []),
        TestCase("ls -l default mode", "ls -l /tmp", ["-rw-r--r--", "root:root", "chmod_smoke"]),
        TestCase("chmod 600", "chmod 600 /tmp/chmod_smoke", []),
        TestCase("ls -l chmod 600", "ls -l /tmp", ["-rw-------", "root:root", "chmod_smoke"]),
        TestCase("rm chmod target", "rm /tmp/chmod_smoke", []),
        TestCase("prepare chown file", "echo shared > /tmp/chown_user_file", []),
        TestCase("chown file to rkc", "chown rkc /tmp/chown_user_file", []),
        TestCase("ls -l chown rkc", "ls -l /tmp", ["-rw-r--r--", "rkc:rkc", "chown_user_file"]),
        TestCase("chown file to root", "chown root /tmp/chown_user_file", []),
        TestCase("ls -l chown root", "ls -l /tmp", ["-rw-r--r--", "root:root", "chown_user_file"]),
        TestCase("chown file back to rkc", "chown 1000:1000 /tmp/chown_user_file", []),
        TestCase("rkxinfo curl", "rkxinfo curl", ["path: /bin/curl", "magic: RKX1", "version: 2", "text:", "stack_pages:"]),
        TestCase("mkdir /tmp/appsmoke", "mkdir /tmp/appsmoke", []),
        TestCase("ls /tmp after mkdir", "ls /tmp", ["appsmoke/"]),
        TestCase("rmdir /tmp/appsmoke", "rmdir /tmp/appsmoke", []),
        TestCase("date", "date", regex=[r"\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}"]),
        TestCase("redirection creates file", "date > /tmp/date_smoke", []),
        TestCase("cat redirected file", "cat /tmp/date_smoke", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("pipe cat", "cat /tmp/date_smoke | cat", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("cp file", "cp /tmp/date_smoke /tmp/date_copy", []),
        TestCase("cat copied file", "cat /tmp/date_copy", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("mv rename file", "mv /tmp/date_copy /tmp/date_moved", []),
        TestCase("cat renamed file", "cat /tmp/date_moved", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("mkdir /tmp/mvdir", "mkdir /tmp/mvdir", []),
        TestCase("prepare rootfs mv file", "date > /mv_cross", []),
        TestCase("mv rootfs file into tmpfs directory", "mv /mv_cross /tmp", []),
        TestCase("cat rootfs file moved into tmpfs", "cat /tmp/mv_cross", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("mv tmpfs file with new name", "mv /tmp/mv_cross /tmp/mv_cross_renamed", []),
        TestCase("cat renamed tmpfs file", "cat /tmp/mv_cross_renamed", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("prepare rootfs mv file explicit dst", "date > /mv2", []),
        TestCase("mv rootfs file to explicit tmpfs path", "mv /mv2 /tmp/mv2", []),
        TestCase("cat explicit tmpfs path", "cat /tmp/mv2", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("mv file into directory", "mv /tmp/date_moved /tmp/mvdir", []),
        TestCase("cat moved file", "cat /tmp/mvdir/date_moved", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("prepare mv multi file a", "date > /tmp/mv_a", []),
        TestCase("prepare mv multi file b", "date > /tmp/mv_b", []),
        TestCase("mv multiple files", "mv /tmp/mv_a /tmp/mv_b /tmp/mvdir", []),
        TestCase("cat moved multi file a", "cat /tmp/mvdir/mv_a", regex=[r"\d{4}/\d{2}/\d{2}"]),
        TestCase("ls moved multi file b", "ls /tmp/mvdir", ["mv_b"]),
        TestCase("rm moved file", "rm /tmp/mvdir/date_moved", []),
        TestCase("rm moved multi file a", "rm /tmp/mvdir/mv_a", []),
        TestCase("rm moved multi file b", "rm /tmp/mvdir/mv_b", []),
        TestCase("rm cross moved file", "rm /tmp/mv_cross_renamed", []),
        TestCase("rm explicit cross moved file", "rm /tmp/mv2", []),
        TestCase("rmdir /tmp/mvdir", "rmdir /tmp/mvdir", []),
        TestCase("rm redirected file", "rm /tmp/date_smoke", []),
    ]
