"""Login, identity, home directory, and unprivileged access test cases."""
from .model import TestCase


def user_tests() -> list[TestCase]:
    """Returns multi-user ownership and permission boundary tests."""
    return [
        TestCase("prepare root sticky file", "echo root-owned > /tmp/root_sticky", []),
        TestCase("prepare root private file", "echo private > /tmp/root_private", []),
        TestCase("chmod root private file", "chmod 600 /tmp/root_private", []),
        TestCase("prepare protected root dir", "mkdir /tmp/root_dir", []),
        TestCase("chmod protected root dir", "chmod 700 /tmp/root_dir", []),
        TestCase("ls root includes home", "ls /", ["home/"]),
        TestCase("ls -l root home owner", "ls -l /", ["drwxr-xr-x", "root:root", "home/"]),
        TestCase("ls -l rkc home owner", "ls -l /home", ["drwxr-xr-x", "rkc:rkc", "rkc/"]),
        TestCase("ls rkc development namespace", "ls /home/rkc", ["bin/", "src/"]),
        TestCase("ls -l rkc development ownership", "ls -l /home/rkc", ["drwxr-xr-x", "rkc:rkc", "bin/", "src/"]),
        TestCase("root can change rkc password", "passwd rkc\nrkc2\nrkc2", ["passwd: password updated"]),
        TestCase("passwd mismatch rejected", "passwd rkc\nleft\nright", ["passwd: password mismatch"]),
        TestCase("switch to rkc with new password", "su rkc\nrkc2", []),
        TestCase("id as rkc", "id", ["uid=1000(rkc)", "gid=1000(rkc)"]),
        TestCase("rkc can restore own password", "passwd rkc\nrkc\nrkc", ["passwd: password updated"]),
        TestCase("rkc cannot change root password", "passwd root\nbad\nbad", ["passwd: failed"]),
        TestCase("user can switch root with password", "su root\nroot", []),
        TestCase("id after su root", "id", ["uid=0", "gid=0"]),
        TestCase("switch back to rkc", "su rkc\nrkc", []),
        TestCase("start nested rkc shell for history", "shell", []),
        TestCase("nested rkc history command", "pwd", ["/home/rkc"]),
        TestCase("nested rkc shell saves history on exit", "exit", []),
        TestCase("rkc history saved under home", "cat /home/rkc/.history", ["pwd", "exit"]),
        TestCase("user history typo path absent", "cat /home.history", ["cat: failed"]),
        TestCase("root history saved under root home", "cat /root/.history", ["su rkc"]),
        TestCase("legacy root history path absent", "cat /.history", ["cat: failed"]),
        TestCase("user can run normal app", "ls /", ["tmp/", "bin/", "home/"]),
        TestCase("user cannot run svc", "svc list", ["permission denied: /bin/svc"]),
        TestCase("user cannot run server binary", "userd", ["cannnot execute /bin/userd directly from shell."]),
        TestCase("user can read /etc", "cat /etc/interface.conf", ["address", "gateway"]),
        TestCase("user cannot chmod root file", "chmod 600 /etc/interface.conf", ["chmod: failed"]),
        TestCase("user cannot chown root file", "chown rkc /etc/interface.conf", ["chown: permission denied"]),
        TestCase("user cannot write /etc", "touch /etc/user_denied", ["failed to create file"]),
        TestCase("user cannot create /usr/bin file", "echo denied > /usr/bin/denied", ["redirect: failed to open /usr/bin/denied"]),
        TestCase("user cannot replace /usr/bin file", "echo denied > /usr/bin/dev_echo", ["redirect: failed to open /usr/bin/dev_echo"]),
        TestCase("user cannot remove /usr/bin file", "rm /usr/bin/dev_echo", ["rm: failed"]),
        TestCase("user cannot write root tmp file", "echo denied > /tmp/root_sticky", ["redirect: failed to open /tmp/root_sticky"]),
        TestCase("user cannot read private root file", "cat /tmp/root_private", ["cat: failed"]),
        TestCase("user cannot list protected root dir", "ls /tmp/root_dir", ["ls: not found"]),
        TestCase("user cannot remove sticky root file", "rm /tmp/root_sticky", ["rm: failed"]),
        TestCase("user can read chowned file", "cat /tmp/chown_user_file", ["shared"]),
        TestCase("user can chmod chowned file", "chmod 600 /tmp/chown_user_file", []),
        TestCase("user chowned file mode visible", "ls -l /tmp", ["-rw-------", "rkc:rkc", "chown_user_file"]),
        TestCase("user can remove own sticky file", "rm /tmp/chown_user_file", []),
        TestCase("user create tmp sticky file", "touch /tmp/user_sticky", []),
        TestCase("user-owned tmp file visible", "ls -l /tmp", ["-rw-r--r--", "rkc:rkc", "user_sticky"]),
        TestCase("user remove own tmp sticky file", "rm /tmp/user_sticky", []),
        TestCase("user can write dev stdout", "echo dev-ok > /dev/stdout", ["dev-ok"]),
        TestCase("user cannot write dev stdin", "echo denied > /dev/stdin", ["redirect: failed to open /dev/stdin"]),
        TestCase("user cd home", "cd /home/rkc", []),
        TestCase("user pwd home", "pwd", ["/home/rkc"]),
        TestCase("user env home defaults", "env", ["HOME=/home/rkc", "PWD=/home/rkc", "PATH=/bin"]),
        TestCase("user cd home src prompt", "cd src", ["rkc@Rk-C:~/src$"]),
        TestCase("user pwd home src", "pwd", ["/home/rkc/src"]),
        TestCase("user env pwd home src", "env", ["HOME=/home/rkc", "PWD=/home/rkc/src"]),
        TestCase("user cd back to home", "cd ..", []),
        TestCase("user pwd home after src", "pwd", ["/home/rkc"]),
        TestCase("user prepare executable in home bin", "cp /bin/echo bin/dev_echo", []),
        TestCase("user chmod executable in home bin", "chmod 755 bin/dev_echo", []),
        TestCase("resolver prefers user executable", "which dev_echo", ["/home/rkc/bin/dev_echo"]),
        TestCase("user executes searched home binary", "dev_echo phase1-user", ["phase1-user"]),
        TestCase("user home binary works in pipe", "dev_echo piped | cat", ["piped"]),
        TestCase("user home binary works in redirect", "dev_echo redirected > phase1.out", []),
        TestCase("user reads redirected home binary output", "cat phase1.out", ["redirected"]),
        TestCase("user cleans redirected home binary output", "rm phase1.out", []),
        TestCase("user prepare cwd executable shadow", "cp /bin/echo ./ls", []),
        TestCase("user chmod cwd executable shadow", "chmod 755 ./ls", []),
        TestCase("bare core command ignores cwd file", "which ls", ["/bin/ls"]),
        TestCase("explicit cwd executable runs", "./ls explicit-local", ["explicit-local"]),
        TestCase("user cleanup cwd executable shadow", "rm ./ls", []),
        TestCase("user prepare search-only executable dir", "mkdir private_exec", []),
        TestCase("user prepare explicit executable", "cp /bin/echo private_exec/run", []),
        TestCase("user chmod explicit executable", "chmod 755 private_exec/run", []),
        TestCase("user hides executable directory listing", "chmod 100 private_exec", []),
        TestCase("explicit path executes without directory read", "./private_exec/run explicit-search", ["explicit-search"]),
        TestCase("user restores executable directory mode", "chmod 700 private_exec", []),
        TestCase("user cleans explicit executable", "rm private_exec/run", []),
        TestCase("user cleans explicit executable dir", "rmdir private_exec", []),
        TestCase("user cleanup home bin executable", "rm bin/dev_echo", []),
        TestCase("user create home bin file", "echo built > bin/local.out", []),
        TestCase("user read home bin file", "cat bin/local.out", ["built"]),
        TestCase("user cleanup home bin file", "rm bin/local.out", []),
        TestCase("user create home src file", "echo source > src/main.nim", []),
        TestCase("user read home src file", "cat src/main.nim", ["source"]),
        TestCase("user cleanup home src file", "rm src/main.nim", []),
        TestCase("user create home file", "echo hello > note.txt", []),
        TestCase("user read home file", "cat note.txt", ["hello"]),
        TestCase("user-owned home file", "ls -l /home/rkc", ["-rw-r--r--", "rkc:rkc", "note.txt"]),
        TestCase("user chmod own file", "chmod 600 note.txt", []),
        TestCase("user chmod own file visible", "ls -l /home/rkc", ["-rw-------", "rkc:rkc", "note.txt"]),
        TestCase("user cleanup own file", "rm note.txt", []),
        TestCase("user cd root after home", "cd /", []),
    ]
