#!/usr/bin/env python3
"""Generate Rk-C version source files and documentation snippets."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


README_START = "<!-- RKC_VERSION_START -->"
README_END = "<!-- RKC_VERSION_END -->"


def read_version(path: Path) -> str:
    version = path.read_text(encoding="utf-8").strip()
    if not version:
        raise SystemExit(f"{path}: version is empty")
    if "\n" in version or "\r" in version:
        raise SystemExit(f"{path}: version must be a single line")
    return version


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_nim(path: Path, version: str) -> None:
    quoted = json.dumps(version)
    content = (
        "## Generated from VERSION by scripts/generate_version.py.\n"
        "## Do not edit this file directly.\n"
        f"const RkcVersion* = {quoted}\n"
        f"const RkcVersionId* = {quoted}\n"
    )
    write_if_changed(path, content)


def update_readme(path: Path, version: str) -> None:
    text = path.read_text(encoding="utf-8")
    start = text.find(README_START)
    end = text.find(README_END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(f"{path}: missing {README_START}/{README_END} markers")

    before = text[: start + len(README_START)]
    after = text[end:]
    replacement = f"\nCurrent version: `{version}`\n"
    write_if_changed(path, before + replacement + after)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version-file", required=True)
    parser.add_argument("--nim-out", required=True)
    parser.add_argument("--readme", required=True)
    args = parser.parse_args()

    version = read_version(Path(args.version_file))
    generate_nim(Path(args.nim_out), version)
    update_readme(Path(args.readme), version)


if __name__ == "__main__":
    main()
