## Provides syscall trace metadata such as syscall display names.
import ../../lib/types
import ../../lib/syscall_ids


## Returns the display name for a syscall number.
proc syscallName*(num: U64): cstring =
  case num:
  of SysWrite: cstring("write")
  of SysRead: cstring("read")
  of SysPs: cstring("ps")
  of SysTicks: cstring("ticks")
  of SysCpuInfo: cstring("cpu_info")
  of SysCpuStaticInfo: cstring("cpu_static_info")
  of SysConsoleInfo: cstring("console_info")
  of SysKmsg: cstring("kmsg")
  of SysRkxTrustList: cstring("rkx_trust_list")
  of SysPoll: cstring("poll")
  of SysExit: cstring("exit")
  of SysLs: cstring("ls")
  of SysTraps: cstring("traps")
  of SysMkdir: cstring("mkdir")
  of SysExec: cstring("exec")
  of SysExecAs: cstring("exec_as")
  of SysWait: cstring("wait")
  of SysUnlink: cstring("unlink")
  of SysRmdir: cstring("rmdir")
  of SysShutdown: cstring("shutdown")
  of SysGetDateTime: cstring("get_date_time")
  of SysReadFile: cstring("read_file")
  of SysWriteFile: cstring("write_file")
  of SysFsInfo: cstring("fs_info")
  of SysRename: cstring("rename")
  of SysGetCwd: cstring("get_cwd")
  of SysSetCwd: cstring("set_cwd")
  of SysGetBitMap: cstring("get_bit_map")
  of SysIpcSend: cstring("ipc_send")
  of SysIpcReceive: cstring("ipc_receive")
  of SysKill: cstring("kill")
  of SysFsServiceRegister: cstring("fs_service_register")
  of SysFsServiceReceive: cstring("fs_service_receive")
  of SysFsServiceReply: cstring("fs_service_reply")
  of SysRawLs: cstring("raw_ls")
  of SysRawMkdir: cstring("raw_mkdir")
  of SysRawUnlink: cstring("raw_unlink")
  of SysRawRmdir: cstring("raw_rmdir")
  of SysRawReadFile: cstring("raw_read_file")
  of SysRawWriteFile: cstring("raw_write_file")
  of SysRawFileSize: cstring("raw_file_size")
  of SysRawReadRange: cstring("raw_read_range")
  of SysRawWriteRange: cstring("raw_write_range")
  of SysRawRename: cstring("raw_rename")
  of SysRawChmod: cstring("raw_chmod")
  of SysRawChown: cstring("raw_chown")
  of SysBlockServiceRegister: cstring("block_service_register")
  of SysBlockServiceReceive: cstring("block_service_receive")
  of SysBlockServiceReply: cstring("block_service_reply")
  of SysRawBlockRead: cstring("raw_block_read")
  of SysRawBlockWrite: cstring("raw_block_write")
  of SysServiceManagerRegister: cstring("service_manager_register")
  of SysServiceRegister: cstring("service_register")
  of SysServiceReady: cstring("service_ready")
  of SysServiceUnregister: cstring("service_unregister")
  of SysYield: cstring("yield")
  of SysSleep: cstring("sleep")
  of SysGetPid: cstring("get_pid")
  of SysGetUid: cstring("get_uid")
  of SysGetGid: cstring("get_gid")
  of SysSetUser: cstring("set_user")
  of SysChmod: cstring("chmod")
  of SysChown: cstring("chown")
  of SysLastError: cstring("last_error")
  of SysServiceList: cstring("service_list")
  of SysIpcTryReceive: cstring("ipc_try_receive")
  of SysIpcSendPacket: cstring("ipc_send_packet")
  of SysIpcReceivePacket: cstring("ipc_receive_packet")
  of SysIpcTryReceivePacket: cstring("ipc_try_receive_packet")
  of SysRawNetInfo: cstring("raw_net_info")
  of SysRawNetInit: cstring("raw_net_init")
  of SysRawNetMac: cstring("raw_net_mac")
  of SysRawNetRecv: cstring("raw_net_recv")
  of SysRawNetSend: cstring("raw_net_send")
  of SysTraceCtl: cstring("trace_ctl")
  of SysEntropy: cstring("entropy")
  of SysOpen: cstring("open")
  of SysReadFd: cstring("read_fd")
  of SysWriteFd: cstring("write_fd")
  of SysClose: cstring("close")
  of SysLseek: cstring("lseek")
  of SysPipe: cstring("pipe")
  of SysDup2: cstring("dup2")
  of SysSignalPoll: cstring("signal_poll")
  of SysBrk: cstring("brk")
  of SysSbrk: cstring("sbrk")
  of SysFdList: cstring("fd_list")
  else: cstring("unknown")
